openapi: "3.1.0"
info:
  title: "Pets API"
  version: 0.0.1
paths:
  /api/pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePetRequest"
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
components:
  schemas:
    CreatePetRequest:
      type: object
      additionalProperties: false
      required:
        - name
        - owner
      properties:
        name:
          $ref: "#/components/schemas/Name"
        owner:
          $ref: "./common-types.yaml#/UserIdentifier"
        birthDate:
          type: string
          format: date
    Name:
      type: string
      minLength: 1
    Pet:
      type: object
      additionalProperties: false
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          $ref: "#/components/schemas/Name"
        owner:
          type: object
          additionalProperties: false
          required:
            - id
            - name
          properties:
            id:
              type: integer
            name:
              $ref: "#/components/schemas/Name"
        birthDate:
          type: string
          format: date
