openapi: "3.1.0"
info:
  title: "Pets API"
  version: 0.0.1
paths:
  /api/pet:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePetRequest"
components:
  schemas:
    CreatePetRequest:
      type: object
      additionalProperties: false
      required:
        - name
        - owner
      properties:
        name:
          $ref: "#/components/schemas/Name"
        owner:
          $ref: "./common-types.yaml#/UserIdentifier"
        birthDate:
          type: string
          format: date
      propertyNames:
        enum: [ "owner", "name", "birthDate" ]
    Name:
      type: string
      minLength: 1
